version: "3.9"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-app
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
      - ./duckdb:/app/duckdb
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_OPTS: "-Xms512m -Xmx1g"
    restart: unless-stopped

volumes:
  metabase-data:
